# config.toml

[profile]
# Default UNC path to users folder on remote / source
SYS_DISK = "C$"
PROGRAM_FILES_DIR = "Program Files (x86)"
USER_PROFILE_SUBPATH = "C$\\Users"
APPDATA_NAME = [
    "*AppData*",
]

[robocopy]
# Common RoboCopy options (robust + multithreaded + restartable + logging-friendly)
ROBOCOPY_OPTIONS = [
    "/S",  # Copy subdirectories, not including empty ones
    "/Z",  # Restartable mode (useful for flaky networks)
    "/XJ",  # Exclude junction points to avoid recursion
    "/SL",  # Exclude symlinks to avoid recursion
    # "/MT:8",  # Multi-threaded copy (8 threads is robocopy default â€” adjust based on environment)
    "/R:1",  # Retry 1 time on failed copies
    "/W:5",  # Wait 5 seconds between retries
    # "/NFL",  # No file list (speeds up logging)
    # "/NDL",  # No directory list
    # "/NP",  # No progress shown in output
    # "/L"  # Only list, do not run
]

# Files known to be machine-specific, unneeded, or locked (registry hives, temp system files)
ROBOCOPY_EXCLUDE_FILES = [
    "*NTUSER.DAT*",
    "*ntuser.dat.LOG1*",
    "*ntuser.dat.LOG2*",
    "*.blf*",
    "*.regtrans*",
    "*UsrClass.dat*",
    "*UsrClass.dat.LOG1*",
    "*UsrClass.dat.LOG2*",
]

# Subfolders within included folders (e.g., Chrome) that should be skipped due to size or irrelevance
ROBOCOPY_EXCLUDE_DIRS = [
    "*Cache*",
    "*Code Cache*",
    "*morgue*",
]

# Folders under AppData\Local worth migrating to preserve user data and settings
APPDATA_LOCAL_INCLUDE_DIRS = [
    "AppData\\Local\\Google\\Chrome\\User Data\\Default",
    "AppData\\Local\\Microsoft\\Edge\\User Data\\Default",
    "AppData\\Local\\Mozilla",
    "AppData\\Local\\MarchNetworks",
    "AppData\\Local\\OpenILS",
    "AppData\\Local\\Hatch",
    "AppData\\Local\\Honeywell",
]

# Roaming profiles - generally smaller and more configuration/history-oriented
APPDATA_ROAMING_INCLUDE_DIRS = [
    "AppData\\Roaming\\Mozilla",
    "AppData\\Roaming\\OpenILS",
    "AppData\\Roaming\\Microsoft\\Windows\\Recent",  # Recent items (shortcuts)
    "AppData\\Roaming\\Microsoft\\Windows\\Recent\\AutomaticDestinations",  # Jump lists (auto)
    "AppData\\Roaming\\Microsoft\\Windows\\Recent\\CustomDestinations",  # Jump lists (custom)
]

[programs]
# Program Files x86 includes - Firefox portable profiles for Evergreen client
PROGRAM_FILES_X86_INCLUDE_DIRS = [
    "Evergreen Web Client\\Data",
]

[registry]
# Registry includes - mapped network drives etc.
REGISTRY_INCLUDES = [
    "HKCU\\Network",
    "HKCU\\Printers",
]
